version: '3.9'
services:
  users_db:
    image: postgres:latest
    container_name: users_db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=users
    ports:
      - "5432:5432"
    networks:
      - epm-orp-imr_imr-network
    volumes:
      - pgdata_user:/var/lib/postgresql/data

networks:
  epm-orp-imr_imr-network:
    driver: bridge
volumes:
  pgdata_user:
